'use client';
import Footer from '@/components/Footer';
import { Box, Stack, ThemeProvider } from '@mui/material';
// import type { Metadata } from 'next';
import './globals.css';
import theme from '@/utils/theme';
import dynamic from 'next/dynamic';
const Header = dynamic(() => import('@/components/Header'), { ssr: false });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-white text-black">
        <ThemeProvider theme={{ ...theme }}>
          <Stack minHeight="100vh">
            <Header />

            <Box component="main" flexGrow={1}>
              {/* <Container
              maxWidth="sm"
              style={{
                backgroundColor: 'red',
              }}
            >
              SM CONTAINER
            </Container>
            <Container
              style={{
                backgroundColor: 'red',
              }}
            >
              MD CONTAINER
            </Container> */}

              {children}
            </Box>
            <Footer />
          </Stack>
        </ThemeProvider>
      </body>
    </html>
  );
}
